name: "ZAP Baseline Scan"

on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan Juice Shop preview instance on Heroku
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@41aee98ebc7cf2802c3beae4e7d4336413a21e43 # v0.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://127.0.0.1'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -j'
